// Programmatic equivalent of `host/node-cli.ts` for use inside tests.
// Runs a NodeHost in-process for a fixed (seed, ticks) and returns the
// emitted SimEvents in declaration order. Heartbeats are suppressed —
// they are wall-clock-cadenced and would inject nondeterminism into the
// byte stream.

import { NodeTransport } from '../../transport/node.js';
import type { Command, SimEvent } from '../../protocol/types.js';

export interface DeterminismRun {
  readonly seed: bigint;
  readonly ticks: bigint;
}

export function runDeterministically(spec: DeterminismRun): readonly SimEvent[] {
  const transport = new NodeTransport({ heartbeatHz: 0 });
  const events: SimEvent[] = [];
  const unsubscribe = transport.onEvent((event) => {
    events.push(event);
  });

  const newRun: Command = {
    kind: 'newRun',
    commandId: 'determinism-newRun',
    seed: spec.seed,
  };
  transport.send(newRun);
  transport.getHost().runUntil(spec.ticks);

  unsubscribe();
  transport.close();
  return events;
}

// JSON.stringify replacer that encodes bigints as decimal strings, matching
// the proto3 JSON convention used by host/node-cli.ts. The two encodings
// must agree byte-for-byte so a golden generated by either path can be
// validated by the other.
function bigintReplacer(_key: string, value: unknown): unknown {
  if (typeof value === 'bigint') return value.toString();
  return value;
}

export function serializeEvents(events: readonly SimEvent[]): string {
  return events.map((e) => JSON.stringify(e, bigintReplacer)).join('\n') + '\n';
}
