// Lay-person legible lineage names. SPEC.md mentions named lineages
// throughout — "Lineages emerge, compete, dominate, and collapse" — but
// leaves the naming scheme as an ARCHITECTURE.md open question. R0 ships
// a deterministic name function: hash the lineage's ordinal, split the
// hash into two halves, index an adjective with the low half and a noun
// with the high half. The combination ("Wandering Pioneers", "Stubborn
// Drifters") gives ~ADJECTIVES × NAMES distinct names — more headroom
// before the birthday paradox produces collisions than a single-word
// scheme.
//
// The word lists are intentionally evocative-but-neutral; the player
// will project meaning onto whichever lineages happen to dominate.
// Adjectives are derived from the ordinal alone, never from the
// lineage's directives or its place in the tree — anything else would
// break determinism.

const NAMES: readonly string[] = [
  'Pioneers',
  'Vagabonds',
  'Drifters',
  'Outliers',
  'Wayfarers',
  'Watchers',
  'Echoes',
  'Embers',
  'Cinders',
  'Sparks',
  'Pilgrims',
  'Wardens',
  'Heralds',
  'Nomads',
  'Stewards',
  'Mariners',
  'Seekers',
  'Founders',
  'Mendicants',
  'Roamers',
  'Surveyors',
  'Cartographers',
  'Mapmakers',
  'Anchorites',
  'Hermits',
  'Shoals',
  'Tides',
  'Currents',
  'Eddies',
  'Whorls',
  'Lanterns',
  'Beacons',
  'Sentinels',
  'Cairns',
  'Lodestones',
  'Compasses',
  'Anvils',
  'Wells',
  'Springs',
  'Crucibles',
  'Forges',
  'Hearths',
  'Kindlers',
  'Banners',
  'Rookeries',
  'Wisps',
  'Motes',
  'Veins',
  'Threads',
  'Filaments',
  'Lattices',
  'Husks',
  'Shells',
  'Vessels',
  'Skiffs',
  'Sloops',
  'Canopies',
  'Boughs',
  'Roots',
  'Tendrils',
  'Ferns',
  'Mosses',
  'Lichens',
  'Reeds',
  'Brambles',
  'Hawthorns',
  'Junipers',
  'Cedars',
  'Spruces',
  'Birches',
  'Magpies',
  'Starlings',
  'Sparrows',
  'Wrens',
  'Swallows',
  'Petrels',
  'Albatrosses',
  'Kestrels',
  'Hawks',
  'Falcons',
  'Owls',
  'Ravens',
  'Crows',
  'Foxes',
  'Hares',
  'Otters',
  'Stoats',
  'Pinedwellers',
  'Reedwalkers',
  'Mistwalkers',
  'Cliffsiders',
  'Highlanders',
  'Lowlanders',
  'Borderers',
  'Crossings',
  'Causeways',
  'Bridges',
  'Fords',
  'Ferries',
  'Quays',
  'Wharves',
  'Marinas',
  'Atolls',
  'Reefs',
  'Lagoons',
  'Sounds',
  'Straits',
  'Channels',
  'Foothills',
  'Saddles',
  'Ridges',
  'Spurs',
  'Talus',
  'Scree',
  'Veldts',
  'Steppes',
  'Tundras',
  'Heaths',
  'Moors',
  'Fens',
  'Bogs',
  'Marshes',
  'Estuaries',
  'Lagoners',
  'Highmen',
  'Skywatchers',
  'Stargazers',
  'Astrolabes',
  'Sextants',
  'Quadrants',
  'Almanacs',
  'Codices',
  'Ledgers',
  'Tallies',
  'Cairnsmen',
  'Haywards',
  'Reeves',
  'Beadles',
  'Vergers',
  'Bedesmen',
  'Almoners',
  'Wassailers',
  'Carollers',
  'Tinkers',
  'Coopers',
  'Smiths',
  'Wrights',
  'Saddlers',
  'Fletchers',
  'Bowyers',
  'Chandlers',
  'Limners',
  'Glaziers',
  'Quarriers',
  'Slaters',
  'Thatchers',
  'Tilers',
  'Knights',
  'Pages',
  'Squires',
  'Yeomen',
  'Carls',
  'Thanes',
  'Gleamers',
  'Glimmers',
  'Glints',
  'Shimmers',
  'Glimmer',
  'Twilights',
  'Gloamings',
  'Mornings',
  'Evenings',
  'Vespers',
  'Matins',
  'Compline',
  'Lauds',
  'Vigils',
  'Watches',
  'Fastnesses',
  'Strongholds',
  'Holdfasts',
  'Bastions',
  'Citadels',
  'Refuges',
  'Sanctuaries',
  'Hospices',
  'Almshouses',
  'Granaries',
  'Storehouses',
  'Caches',
  'Stockpiles',
  'Reserves',
  'Outposts',
  'Caravans',
  'Companies',
  'Fellowships',
  'Wakes',
  'Reckonings',
  'Tidings',
  'Daybreaks',
];

const ADJECTIVES: readonly string[] = [
  'Wandering',
  'Stubborn',
  'Errant',
  'Distant',
  'Quiet',
  'Silent',
  'Fading',
  'Rising',
  'Quickening',
  'Patient',
  'Wary',
  'Bold',
  'Cautious',
  'Restless',
  'Steady',
  'Wild',
  'Lonely',
  'Gathered',
  'Scattered',
  'Steadfast',
  'Wayward',
  'Hidden',
  'Lost',
  'Found',
  'Ancient',
  'Young',
  'Far',
  'High',
  'Low',
  'Deep',
  'Shallow',
  'Bright',
  'Dim',
  'Faint',
  'Sharp',
  'Keen',
  'Idle',
  'Glimmering',
  'Whispering',
  'Singing',
  'Drowsy',
  'Watchful',
  'Hungry',
  'Sated',
  'Threadbare',
  'Spare',
  'Lean',
  'Hollow',
  'Roving',
  'Tireless',
  'Weary',
  'Hopeful',
  'Resolute',
  'Forsaken',
  'Renewed',
  'Unbroken',
  'Mended',
  'Frayed',
  'Tangled',
  'Branching',
  'Trailing',
  'Vagrant',
  'Drifting',
  'Stoic',
  'Vigilant',
  'Solemn',
  'Brisk',
  'Tender',
  'Stern',
  'Mild',
  'Fierce',
  'Gentle',
  'Hushed',
  'Misty',
  'Gilded',
  'Tarnished',
  'Worn',
  'Polished',
  'Plain',
  'Ornate',
  'Curious',
  'Earnest',
  'Aimless',
  'Deliberate',
  'Sudden',
  'Lingering',
  'Fleeting',
  'Enduring',
  'Sober',
  'Joyful',
  'Defiant',
  'Eager',
  'Reluctant',
  'Forgotten',
  'Remembered',
  'Twilit',
  'Moonlit',
  'Gleaming',
  'Smouldering',
  'Battered',
];

const FNV_OFFSET = 0xcbf29ce484222325n;
const FNV_PRIME = 0x100000001b3n;
const U64_MASK = 0xffffffffffffffffn;

function fnv1a(value: bigint): bigint {
  let hash = FNV_OFFSET;
  let v = value & U64_MASK;
  for (let i = 0; i < 8; i += 1) {
    const byte = v & 0xffn;
    hash = ((hash ^ byte) * FNV_PRIME) & U64_MASK;
    v >>= 8n;
  }
  return hash;
}

// Deterministic name for a lineage given its ordinal. Splits the FNV
// hash into two 32-bit halves and uses each as an independent index
// into the adjective and noun lists. A different seed produces the
// same name space but in a different order of speciation.
export function lineageName(ordinal: bigint): string {
  const hash = fnv1a(ordinal);
  const adjIdx = Number((hash & 0xffffffffn) % BigInt(ADJECTIVES.length));
  const nounIdx = Number((hash >> 32n) % BigInt(NAMES.length));
  const adjective = ADJECTIVES[adjIdx];
  const noun = NAMES[nounIdx];
  if (adjective === undefined || noun === undefined) return `Lineage-${ordinal.toString()}`;
  return `${adjective} ${noun}`;
}
