// Lay-person legible lineage names. SPEC.md mentions named lineages
// throughout — "Lineages emerge, compete, dominate, and collapse" — but
// leaves the naming scheme as an ARCHITECTURE.md open question. R0 ships
// a deterministic name function that picks an evocative word from a
// curated list, indexed by a hash of the lineage's ordinal.
//
// The word list is intentionally evocative-but-neutral; the player will
// project meaning onto whichever lineages happen to dominate.

const NAMES: readonly string[] = [
  'Pioneers',
  'Vagabonds',
  'Drifters',
  'Outliers',
  'Wayfarers',
  'Watchers',
  'Echoes',
  'Embers',
  'Cinders',
  'Sparks',
  'Pilgrims',
  'Wardens',
  'Heralds',
  'Nomads',
  'Stewards',
  'Mariners',
  'Seekers',
  'Founders',
  'Mendicants',
  'Roamers',
  'Surveyors',
  'Cartographers',
  'Mapmakers',
  'Anchorites',
  'Hermits',
  'Shoals',
  'Tides',
  'Currents',
  'Eddies',
  'Whorls',
  'Lanterns',
  'Beacons',
  'Sentinels',
  'Cairns',
  'Lodestones',
  'Compasses',
  'Anvils',
  'Wells',
  'Springs',
  'Crucibles',
  'Forges',
  'Hearths',
  'Kindlers',
  'Banners',
  'Rookeries',
  'Wisps',
  'Motes',
  'Veins',
  'Threads',
  'Filaments',
  'Lattices',
  'Husks',
  'Shells',
  'Vessels',
  'Skiffs',
  'Sloops',
  'Canopies',
  'Boughs',
  'Roots',
  'Tendrils',
  'Ferns',
  'Mosses',
  'Lichens',
  'Reeds',
  'Brambles',
  'Hawthorns',
  'Junipers',
  'Cedars',
  'Spruces',
  'Birches',
  'Magpies',
  'Starlings',
  'Sparrows',
  'Wrens',
  'Swallows',
  'Petrels',
  'Albatrosses',
  'Kestrels',
  'Hawks',
  'Falcons',
  'Owls',
  'Ravens',
  'Crows',
  'Foxes',
  'Hares',
  'Otters',
  'Stoats',
  'Pinedwellers',
  'Reedwalkers',
  'Mistwalkers',
  'Cliffsiders',
  'Highlanders',
  'Lowlanders',
  'Borderers',
  'Crossings',
  'Causeways',
  'Bridges',
  'Fords',
  'Ferries',
  'Quays',
  'Wharves',
  'Marinas',
  'Atolls',
  'Reefs',
  'Lagoons',
  'Sounds',
  'Straits',
  'Channels',
  'Foothills',
  'Saddles',
  'Ridges',
  'Spurs',
  'Talus',
  'Scree',
  'Veldts',
  'Steppes',
  'Tundras',
  'Heaths',
  'Moors',
  'Fens',
  'Bogs',
  'Marshes',
  'Estuaries',
  'Lagoners',
  'Highmen',
  'Skywatchers',
  'Stargazers',
  'Astrolabes',
  'Sextants',
  'Quadrants',
  'Almanacs',
  'Codices',
  'Ledgers',
  'Tallies',
  'Cairnsmen',
  'Hayward',
  'Wardens',
  'Reeves',
  'Beadles',
  'Vergers',
  'Bedesmen',
  'Almoners',
  'Wassailers',
  'Carollers',
  'Tinkers',
  'Coopers',
  'Smiths',
  'Wrights',
  'Saddlers',
  'Fletchers',
  'Bowyers',
  'Chandlers',
  'Limners',
  'Glaziers',
  'Quarriers',
  'Slaters',
  'Thatchers',
  'Tilers',
  'Stewards',
  'Heralds',
  'Knights',
  'Pages',
  'Squires',
  'Yeomen',
  'Carls',
  'Thanes',
  'Gleamers',
  'Glimmers',
  'Glints',
  'Shimmers',
  'Glimmer',
  'Twilights',
  'Gloamings',
  'Mornings',
  'Evenings',
  'Vespers',
  'Matins',
  'Compline',
  'Lauds',
  'Vigils',
  'Watches',
  'Fastnesses',
  'Strongholds',
  'Holdfasts',
  'Bastions',
  'Citadels',
  'Refuges',
  'Sanctuaries',
  'Hospices',
  'Almshouses',
  'Granaries',
  'Storehouses',
  'Caches',
  'Stockpiles',
  'Reserves',
];

const FNV_OFFSET = 0xcbf29ce484222325n;
const FNV_PRIME = 0x100000001b3n;
const U64_MASK = 0xffffffffffffffffn;

function fnv1a(value: bigint): bigint {
  let hash = FNV_OFFSET;
  let v = value & U64_MASK;
  for (let i = 0; i < 8; i += 1) {
    const byte = v & 0xffn;
    hash = ((hash ^ byte) * FNV_PRIME) & U64_MASK;
    v >>= 8n;
  }
  return hash;
}

// Deterministic name for a lineage given its ordinal. The seed of the
// run is implicitly encoded by the founding probe's lineage assignments;
// a different seed produces the same name list but in a different order
// of speciation.
export function lineageName(ordinal: bigint): string {
  const idx = Number(fnv1a(ordinal) % BigInt(NAMES.length));
  return NAMES[idx] ?? `Lineage-${ordinal.toString()}`;
}
