import { describe, expect, it } from 'vitest';
import { Xoshiro256ss, splitmix64Expand } from './rng.js';

// Golden vectors generated by an independent Python reference implementation
// of the canonical splitmix64 / xoshiro256** algorithms. These values define
// the contract: any future implementation of the sim (the Rust port included)
// must reproduce them byte-for-byte from the same seed.

describe('splitmix64Expand', () => {
  it('produces the documented sequence from seed=42', () => {
    const state = splitmix64Expand(42n);
    expect(state).toEqual([
      0xbdd732262feb6e95n,
      0x28efe333b266f103n,
      0x47526757130f9f52n,
      0x581ce1ff0e4ae394n,
    ]);
  });

  it('handles seed=0 without producing all-zero state', () => {
    const state = splitmix64Expand(0n);
    expect(state.every((s) => s !== 0n)).toBe(true);
  });
});

describe('Xoshiro256ss', () => {
  it('produces the golden 16-output sequence from seed=42', () => {
    const rng = Xoshiro256ss.fromSeed(42n);
    const golden: bigint[] = [
      0x15780b2e0c2ec716n,
      0x6104d9866d113a7en,
      0xae17533239e499a1n,
      0xecb8ad4703b360a1n,
      0xfde6dc7fe2ec5e64n,
      0xc50da53101795238n,
      0xb82154855a65ddb2n,
      0xd99a2743ebe60087n,
      0xc2e96e726e97647en,
      0x9556615f775fbc3dn,
      0xaeb53b340c103971n,
      0x4a69db9873af8965n,
      0xcd0feda93006c6b6n,
      0x52480865a4b42742n,
      0xb60dec3bf2d887cdn,
      0xe0b55a68b96677fan,
    ];
    const actual = golden.map(() => rng.nextU64());
    expect(actual).toEqual(golden);
  });

  it('produces the golden sequence from seed=0', () => {
    const rng = Xoshiro256ss.fromSeed(0n);
    expect([rng.nextU64(), rng.nextU64(), rng.nextU64(), rng.nextU64()]).toEqual([
      0x99ec5f36cb75f2b4n,
      0xbf6e1f784956452an,
      0x1a5f849d4933e6e0n,
      0x6aa594f1262d2d2cn,
    ]);
  });

  it('is deterministic: same seed yields identical sequence', () => {
    const a = Xoshiro256ss.fromSeed(12345n);
    const b = Xoshiro256ss.fromSeed(12345n);
    for (let i = 0; i < 100; i++) {
      expect(a.nextU64()).toBe(b.nextU64());
    }
  });

  it('round-trips through state() / fromState()', () => {
    const rng = Xoshiro256ss.fromSeed(99n);
    for (let i = 0; i < 7; i++) rng.nextU64();
    const snapshot = rng.state();
    const before = [rng.nextU64(), rng.nextU64(), rng.nextU64()];

    const restored = Xoshiro256ss.fromState(snapshot);
    const after = [restored.nextU64(), restored.nextU64(), restored.nextU64()];

    expect(after).toEqual(before);
  });

  it('rejects all-zero state', () => {
    expect(() => Xoshiro256ss.fromState([0n, 0n, 0n, 0n])).toThrow();
  });

  it('all outputs fit in u64', () => {
    const rng = Xoshiro256ss.fromSeed(7n);
    for (let i = 0; i < 1000; i++) {
      const v = rng.nextU64();
      expect(v >= 0n).toBe(true);
      expect(v <= 0xffffffffffffffffn).toBe(true);
    }
  });
});
