import type { ReplicationEvent, SimEvent, SpeciationEvent } from '../protocol/types.js';
import type { Directive } from './directive.js';
import { firmwareDiverged, type Lineage } from './lineage.js';
import { lineageName } from './lineage-names.js';
import { maybeMutate } from './mutation.js';
import type { Probe, SimState } from './state.js';
import { LineageId, ProbeId, SimTick } from './types.js';

// Advance the simulation by one tick. SPEC.md R0 — Petri Dish: probes
// replicate per their firmware; no resources, no death (those land at R1).
//
// Determinism notes:
//   - PRNG draws are consumed in a fixed order: probes existing at tick start,
//     iterated in Map insertion order (which JS guarantees). Children born
//     this tick are NOT iterated until the next tick.
//   - Speciation is a deterministic function of firmware comparison; no PRNG
//     draws are consumed by clustering.
//
// `events`, if provided, is appended to with the SimEvents generated by this
// tick — replication events for every birth, speciation events for every
// new lineage. Heartbeat (Tick) events are not emitted here; the host owns
// heartbeat cadence because it is wall-clock-driven and best-effort.
export function tick(state: SimState, events?: SimEvent[]): void {
  state.simTick = SimTick(state.simTick + 1n);

  const ids = [...state.probes.keys()];
  for (const id of ids) {
    const probe = state.probes.get(id);
    if (probe === undefined) continue;

    for (const directive of probe.firmware) {
      maybeApply(state, probe, directive, events);
    }
  }
}

export function tickN(state: SimState, n: bigint, events?: SimEvent[]): void {
  for (let i = 0n; i < n; i++) tick(state, events);
}

function maybeApply(
  state: SimState,
  probe: Probe,
  directive: Directive,
  events: SimEvent[] | undefined,
): void {
  switch (directive.kind) {
    case 'replicate':
      maybeReplicate(state, probe, directive.threshold, events);
      return;
  }
}

function maybeReplicate(
  state: SimState,
  parent: Probe,
  threshold: bigint,
  events: SimEvent[] | undefined,
): void {
  const roll = state.rng.nextU64();
  if (roll >= threshold) return;

  const mutation = maybeMutate(state.rng, parent.firmware);
  const childFirmware = mutation.firmware;

  const childId = ProbeId(`P${state.nextProbeOrdinal}`);
  state.nextProbeOrdinal += 1n;

  // Lineage clustering: if the child's firmware has drifted past the
  // divergence threshold from its parent's lineage reference, the child
  // founds a new lineage. Otherwise it inherits the parent's.
  const parentLineage = state.lineages.get(parent.lineageId);
  if (parentLineage === undefined) {
    throw new Error(`lineage ${parent.lineageId} missing from state`);
  }

  let childLineageId = parent.lineageId;
  if (firmwareDiverged(childFirmware, parentLineage.referenceFirmware)) {
    const ordinal = state.nextLineageOrdinal;
    childLineageId = LineageId(`L${ordinal.toString()}`);
    state.nextLineageOrdinal += 1n;
    const newLineageName = lineageName(ordinal);
    const newLineage: Lineage = {
      id: childLineageId,
      name: newLineageName,
      founderProbeId: childId,
      parentLineageId: parent.lineageId,
      referenceFirmware: childFirmware,
      foundedAtTick: state.simTick,
    };
    state.lineages.set(childLineageId, newLineage);

    if (events !== undefined) {
      const speciation: SimEvent = {
        kind: 'speciation',
        simTick: state.simTick,
        parentLineageId: parent.lineageId,
        newLineageId: childLineageId,
        newLineageName,
        founderProbeId: childId,
      } satisfies SpeciationEvent & { simTick: bigint };
      events.push(speciation);
    }
  }

  const child: Probe = {
    id: childId,
    lineageId: childLineageId,
    bornAtTick: state.simTick,
    firmware: childFirmware,
  };
  state.probes.set(childId, child);

  if (events !== undefined) {
    const replication: SimEvent = {
      kind: 'replication',
      simTick: state.simTick,
      parentProbeId: parent.id,
      childProbeId: childId,
      lineageId: childLineageId,
      mutated: mutation.mutated,
    } satisfies ReplicationEvent & { simTick: bigint };
    events.push(replication);
  }
}
